[package]
name = "airqc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.1", default-features = false }
cortex-m-rtic = "0.6.0-alpha.5"
crc-any = { version = "2.3.12", default-features = false }
embedded-graphics = "0.7.1"
panic-itm = "0.4.2"
st7789 = "0.6.0"
stm32f4xx-hal = { version = "0.9.0", features = ["fsmc_lcd", "rt", "stm32f413"] }

[patch.crates-io]
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal" }
